//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiclaunch_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public string branch { get; set; }
    
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
